services:
  - type: web
    name: securevision-server
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        generateValue: true
      - key: AES_SECRET
        generateValue: true
      - key: CLIENT_ORIGIN
        sync: false
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DB
        value: face_verification_db
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FACE_SERVICE_URL
        sync: false

  - type: web
    name: securevision-face-service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port 5001
    envVars:
      - key: TF_USE_LEGACY_KERAS
        value: "0"
